layout_spectrum: 0.7447158
typography_spectrum: 0.8761312
color:
  saturation: 0.1376518
  lightness: 0.3461061
  brandStrength: 0.8679305
  rhythmicContrast: 0.5885764
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Ianjones
